@port=4004
@server=http://localhost:{{port}}
@username=alice
@password=


### Materials
# @name Materials_GET
GET {{server}}/odata/v4/shortage/Materials
Authorization: Basic {{username}}:{{password}}


### MaterialDescriptions
# @name MaterialDescriptions_GET
GET {{server}}/odata/v4/shortage/Materials?$expand=to_Description&$top=5
Authorization: Basic {{username}}:{{password}}




### ProductionOrders
# @name ProductionOrders_GET
GET {{server}}/odata/v4/shortage/ProductionOrders
Authorization: Basic {{username}}:{{password}}
